"/Users/hrudolph/Library/Logs/discrawl/tail-native.log"
"/Users/hrudolph/Library/Logs/discrawl/tail-native.err.log"
"/Users/hrudolph/Library/Logs/discrawl/status-native.log"
"/Users/hrudolph/Library/Logs/discrawl/status-native.err.log"
"/Users/hrudolph/Library/Logs/discrawl/logrotate.err.log"
{
 size 100M
 rotate 7
 copytruncate
 compress
 delaycompress
 missingok
 notifempty
}
